{"name": "test_euality", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 8 > 8", "trace": "@pytest.mark.xfail\n    def test_euality():\n        num=8\n>       assert num>8\nE       assert 8 > 8\n\ntest_square.py:22: AssertionError"}, "start": 1670926054766, "stop": 1670926054766, "uuid": "44f4b6b6-c082-4cc0-85e7-66c80da1f839", "historyId": "69150a7e4586ce32768940d74a9f04ca", "testCaseId": "e6a22aae02d95eca1904bf110e6abb48", "fullName": "test_square#test_euality", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_square"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "14116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_square"}]}