{"name": "test_less_than_5[6]", "status": "failed", "statusDetails": {"message": "AssertionError: given number is not less than 5\nassert False", "trace": "data = 6\n\n    @pytest.mark.parametrize(\"data\", [8,5,6,3])\n    def test_less_than_5(data):\n        if data<5:\n            assert True\n        else:\n>           assert False, \"given number is not less than 5\"\nE           AssertionError: given number is not less than 5\nE           assert False\n\ntest_multiplication.py:27: AssertionError"}, "parameters": [{"name": "data", "value": "6"}], "start": 1670926238117, "stop": 1670926238117, "uuid": "63387ada-27f6-47b0-92d3-44911ead351b", "historyId": "724b2def11934265d02c9019c4d84cd6", "testCaseId": "bff07a8edb5163779e72e449c23ae71b", "fullName": "test_multiplication#test_less_than_5", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "13904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}