{"name": "test_less_than_5[6]", "status": "failed", "statusDetails": {"message": "AssertionError: given number is not less than 5\nassert False", "trace": "data = 6\n\n    @pytest.mark.parametrize(\"data\", [8,5,6,3])\n    def test_less_than_5(data):\n        if data<5:\n            assert True\n        else:\n>           assert False, \"given number is not less than 5\"\nE           AssertionError: given number is not less than 5\nE           assert False\n\ntest_multiplication.py:27: AssertionError"}, "parameters": [{"name": "data", "value": "6"}], "start": 1670925497129, "stop": 1670925497130, "uuid": "e03fea8f-6115-43ff-a11b-8b14f55cc54d", "historyId": "724b2def11934265d02c9019c4d84cd6", "testCaseId": "bff07a8edb5163779e72e449c23ae71b", "fullName": "test_multiplication#test_less_than_5", "labels": [{"name": "suite", "value": "test_multiplication"}, {"name": "host", "value": "DESKTOP-D9P5RJB"}, {"name": "thread", "value": "6700-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_multiplication"}]}